services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8888:3000"
    volumes:
      - ./portfolio:/app
      - node_modules:/app/node_modules
    command: yarn dev

volumes:
  node_modules:
