version: "3"

includes:
  nd: ./taskfiles/node.yml
  gc: ./taskfiles/gcloud.yml
  gh: ./taskfiles/github.yml
  tf: ./taskfiles/terraform.yml

env:
  TF_CLI_CONFIG_FILE: "/root/.terraform.d/credentials.tfrc.json"
  TFC_ORG_NAME: "kamono-personal"
  TFC_SERVICE_ACCOUNT_ID: "tfc-service-account"
  WORKLOAD_IDENTITY_POOL_ID: "kamono-tfc-pool"
  WORKLOAD_IDENTITY_PROVIDER_ID: "kamono-tfc-provider-id"

vars:
  ACCOUNT:
    sh: gcloud auth list --format="value(account)" --filter=status:ACTIVE
  PROJECT_ID:
    sh: gcloud config get-value project
  WORKLOAD_IDENTITY_POOL_FULL_ID:
    sh: (gcloud iam workload-identity-pools list --location="global" --format="value(name)") || echo ""
  WORKLOAD_IDENTITY_PROVIDER_FULL_ID:
    sh: (gcloud iam workload-identity-pools providers list --location="global" --workload-identity-pool="{{.WORKLOAD_IDENTITY_POOL_FULL_ID}}" --format="value(name)") || echo ""

tasks:
  clean:
    prompt: すべてのキャッシュデータを削除しますか？
    cmds:
      - task: nd:clean
      - task: gc:clean
      - task: gh:clean

  init:
    prompt: 新規プロジェクトを作成しますか？
    cmds:
      # - task: nd:install
      - task: gc:enable_apis
      - echo "google cloudの設定をしています。数秒お待ちください。"
      - sleep 5
      - task: create_oidc
      - task: set_gh_secret

  reset:
    prompt: すべての設定をリセットしますか？google cloudのサービスアカウントは削除されます。
    cmds:
      - task: nd:clean
      - task: gc:reset
      - task: gh:reset

  set_gh_secret:
    deps: [create_oidc]
    cmds:
      - task: gh:set_secret
        vars:
          SECRET_NAME: "WORKLOAD_IDENTITY_PROVIDER"
          SECRET_VALUE: "{{.WORKLOAD_IDENTITY_PROVIDER_ID}}"
      - task: gh:set_secret
        vars:
          SECRET_NAME: "SERVICE_ACCOUNT"
          SECRET_VALUE: "{{.TFC_SERVICE_ACCOUNT_ID}}@{{.PROJECT_ID}}.iam.gserviceaccount.com"

  create_oidc:
    deps: [gc:login-applications]
    cmds:
      - task: tf:create_oidc
        vars:
          PROJECT_ID: "{{.PROJECT_ID}}"
          TFC_ORG_NAME: "{{.TFC_ORG_NAME}}"
          WORKLOAD_IDENTITY_POOL_ID: "{{.WORKLOAD_IDENTITY_POOL_ID}}"
          WORKLOAD_IDENTITY_PROVIDER_ID: "{{.WORKLOAD_IDENTITY_PROVIDER_ID}}"
          TFC_SERVICE_ACCOUNT_ID: "{{.TFC_SERVICE_ACCOUNT_ID}}"
    status:
      - gcloud iam service-accounts list --format="value(email)" --filter="displayName:Terraform"
